# Default values for dh-ms-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/deployhub/dh-ms-nginx
  tag: svccat-v9.0.0.3327-gdedbec7
  pullPolicy: Always

ingress:
  enum:
    alb: "OFF"
    volumemnt: ""
    sslcert: "ON"
    ssloff: "OFF"

  type: ssloff   # alb, volumemnt, sslcert, ssloff  
  alb_certificate_arn: 
  alb_subnets: 
  sslcert:
    chainedcert : |
      -----BEGIN CERTIFICATE-----
      -----END CERTIFICATE-----
    privatekkey: |
      -----BEGIN PRIVATE KEY-----
      -----END PRIVATE KEY-----
  