apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: jwtkeys
data:
  id_rsa: |
  {{ .Values.jwt.privatekey | b64enc | indent 2 }}
  id_rsa.pub: |
  {{ .Values.jwt.publickey | b64enc | indent 2 }}
